Agregado modulo de instalacion de Pyhton, actualizado .gitconfig

diff --git a/CustomRiceInstaller b/CustomRiceInstaller
--- a/CustomRiceInstaller
+++ b/CustomRiceInstaller
@@ -197,10 +197,81 @@ fi
 
 
 sleep 2
+clear
 
 
 
+########## ---------- Install Python ---------- ##########
 
+
+
+logo "Install python"
+
+printf "Desea instalar paquetes necesarios para un entorno de desarrollo en python? escriba 'n' para saltar esta parte. Si tu respuesta es 'y' Se verificara cuales paquetes estan instalados y cuales no, procediendo a la instalacion si es necesario.\n\n"
+
+while true; do
+    read -rp "Do you want to install Python Dev Workspace tools? (y/n): " python_packages
+    if [[ "$python_packages" == "y" || "$python_packages" == "n" ]]; then
+        break
+    else
+        echo "Invalid input. Please enter 'y' or 'n'."
+    fi
+done
+
+if [[ $python_packages == "y" ]]; then
+logo "Installing needed packages.."
+
+
+dependencias=(
+python \
+python-pip \
+python-virtualenv \
+python-pytest \
+poetry \
+python-flake8-black \
+python-black \
+python-ipdb \
+python-coverage \
+python-sphinx \
+postgresql \
+sqlitebrowser \
+python-django \
+python-flask \
+jupyter-notebook  \
+python-numpy \
+python-pandas \
+python-matplotlib \
+python-scipy \
+python-pynvim \
+ripgrep \
+fd \
+) 
+
+is_installed() {
+    pacman -Q "$1" &> /dev/null
+}
+
+printf "%s%sChecking for required packages...%s\n" "${BLD}" "${CBL}" "${CNC}"
+	for paquete in "${dependencias[@]}"; do
+		if ! is_installed "$paquete"; then
+			if sudo pacman -S "$paquete" --noconfirm >/dev/null 2>> RiceError.log; then
+				printf "%s%s%s %shas been installed succesfully.%s\n" "${BLD}" "${CYE}" "$paquete" "${CBL}" "${CNC}"
+				sleep 1
+			else
+				printf "%s%s%s %shas not been installed correctly. See %sRiceError.log %sfor more details.%s\n" "${BLD}" "${CYE}" "$paquete" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
+				sleep 1
+			fi
+		else
+			printf '%s%s%s %sis already installed on your system!%s\n' "${BLD}" "${CYE}" "$paquete" "${CGR}" "${CNC}"
+			sleep 1
+		fi
+	done
+
+fi
+
+sleep 2
+
+logo "Install is complete"
 
 
 
